//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 2:24:23 AM on Wednesday, January 06, 1999
//
//	Generated for file: C:\WORK\basswood\8queens\Src\8queens.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"8 Queens"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCheckButton                           1001	//(Left Origin = 138, Top Origin = 123, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainFindButton                            1007	//(Left Origin = 138, Top Origin = 144, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define MainRotRightButton                        1010	//(Left Origin = 138, Top Origin = 60, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define MainFlipVertButton                        1011	//(Left Origin = 138, Top Origin = 81, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define MainFlipHorizButton                       1012	//(Left Origin = 138, Top Origin = 102, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define MainClearButton                           1014	//(Left Origin = 138, Top Origin = 18, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define MainRotLeftButton                         1015	//(Left Origin = 138, Top Origin = 39, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define MainRotRightBitMap                        1002	//(Left Origin = 138, Top Origin = 60, Bitmap Resource ID = 1002, Usable = 1)
#define MainRotLeftBitMap                         1001	//(Left Origin = 138, Top Origin = 39, Bitmap Resource ID = 1001, Usable = 1)
#define MainFlipVertBitMap                        1003	//(Left Origin = 138, Top Origin = 81, Bitmap Resource ID = 1003, Usable = 1)
#define MainFindBitMap                            1013	//(Left Origin = 138, Top Origin = 144, Bitmap Resource ID = 1013, Usable = 1)
#define MainFlipHorizBitMap                       1004	//(Left Origin = 138, Top Origin = 102, Bitmap Resource ID = 1004, Usable = 1)
#define MainUnnamed1013BitMap                     1010	//(Left Origin = 138, Top Origin = 18, Bitmap Resource ID = 1010, Usable = 1)
#define MainCheckBitMap                           1011	//(Left Origin = 138, Top Origin = 123, Bitmap Resource ID = 1011, Usable = 1)


//	Resource: tFRM 1100
#define GeneratingForm                            1100	//(Left Origin = 2, Top Origin = 98, Width = 156, Height = 60, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GeneratingGenCancelButton                 1103	//(Left Origin = 50, Top Origin = 44, Width = 52, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GeneratingProgressGadget                  1102	//(Left Origin = 5, Top Origin = 20, Width = 140, Height = 14, Usable = 1)


//	Resource: tFRM 1200
#define BrowseForm                                1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define BrowseUnnamed1201Button                   1201	//(Left Origin = 113, Top Origin = 147, Width = 46, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BrowseGoButton                            1211	//(Left Origin = 72, Top Origin = 147, Width = 30, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BrowseRotRightButton                      1216	//(Left Origin = 136, Top Origin = 40, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define BrowseFlipVertButton                      1217	//(Left Origin = 136, Top Origin = 61, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define BrowseFlipHorizButton                     1218	//(Left Origin = 136, Top Origin = 82, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define BrowseRotLeftButton                       1219	//(Left Origin = 136, Top Origin = 19, Width = 16, Height = 16, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol)
#define BrowseUnnamed1209BitMap                   1002	//(Left Origin = 136, Top Origin = 40, Bitmap Resource ID = 1002, Usable = 1)
#define BrowseUnnamed1210BitMap                   1001	//(Left Origin = 136, Top Origin = 19, Bitmap Resource ID = 1001, Usable = 1)
#define BrowseUnnamed1214BitMap                   1003	//(Left Origin = 136, Top Origin = 61, Bitmap Resource ID = 1003, Usable = 1)
#define BrowseUnnamed1215BitMap                   1004	//(Left Origin = 136, Top Origin = 82, Bitmap Resource ID = 1004, Usable = 1)
#define BrowseSolnField                           1205	//(Left Origin = 0, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define BrowseGridGadget                          1202	//(Left Origin = 0, Top Origin = 13, Width = 130, Height = 130, Usable = 1)
#define BrowseStatusLabel                         1204	//(Left Origin = 71, Top Origin = 0, Usable = 1, Font = Standard)
#define BrowseScrollUpRepeating                   1212	//(Left Origin = 46, Top Origin = 145, Width = 13, Height = 8, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)
#define BrowseScrollDownRepeating                 1213	//(Left Origin = 46, Top Origin = 152, Width = 13, Height = 8, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Symbol 7)


//	Resource: tFRM 1300
#define AboutForm                                 1300	//(Left Origin = 2, Top Origin = 32, Width = 156, Height = 126, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutUnnamed1303Button                    1303	//(Left Origin = 8, Top Origin = 106, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutEggButtonButton                      1304	//(Left Origin = 121, Top Origin = 95, Width = 22, Height = 22, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1301BitMap                    1012	//(Left Origin = 121, Top Origin = 95, Bitmap Resource ID = 1012, Usable = 1)
#define AboutUnnamed1302Label                     1302	//(Left Origin = 12, Top Origin = 16, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define SuccessAlert                              1100
#define SuccessOK                                 0

//	Resource: Talt 1200
#define NoSolnsAlert                              1200
#define NoSolnsOK                                 0

//	Resource: Talt 1300
#define EggAlert                                  1300
#define EggOK                                     0

//	Resource: Talt 1000
#define NoQueensAlert                             1000
#define NoQueensOK                                0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsHelp                           1000	// Command Key: H
#define MainOptionsAbout8Queens                   1001

//	Resource: tSTR 1100
#define BrowseHelpString                          1100	// "The 8 Queens browser allows you to browse all of the possible solutions to the 8 queens problem.  Use the lo"

//	Resource: tSTR 1000
#define SolveHelpString                           1000	// "8 Queens is a classic puzzle.  Try to place 8 queens on a standard chessboard so that no queen can attack any other.  This means that no two queens can share the same horizon"

//	Resource: PICT 1000
#define queenBitmap                               1000
//	Resource: PICT 1001
#define RotLeftBitmap                             1001
//	Resource: PICT 1002
#define RotRightBitmap                            1002
//	Resource: PICT 1003
#define FlipVertBitmap                            1003
//	Resource: PICT 1004
#define FlipHorizBitmap                           1004
//	Resource: PICT 1005
#define NextBitmap                                1005
//	Resource: PICT 1006
#define PrevBitmap                                1006
//	Resource: PICT 1100
#define queenwhiteBitmap                          1100
//	Resource: PICT 1300
#define queenblackBitmap                          1300
//	Resource: PICT 1400
#define queenblackrevBitmap                       1400
//	Resource: PICT 1500
#define allwhiteBitmap                            1500
//	Resource: PICT 1200
#define queenwhiterevBitmap                       1200
//	Resource: PICT 1600
#define allblackBitmap                            1600
//	Resource: PICT 1012
#define QueenIconBitmap                           1012
//	Resource: PICT 1010
#define EraserBitmap                              1010
//	Resource: PICT 1011
#define CheckmarkBitmap                           1011
//	Resource: PICT 1013
#define FindmarkBitmap                            1013
//	Resource: PICT 1201
#define queenwhitefixedBitmap                     1201
//	Resource: PICT 1401
#define queenblackfixedBitmap                     1401